<?php

return [
    // Keep bcrypt as the default driver
    'driver' => env('HASH_DRIVER', 'bcrypt'),

    'bcrypt' => [
        'rounds' => env('BCRYPT_ROUNDS', 12),
        // Allow verifying any password generated by PHP's password_hash
        // regardless of the algorithm encoded in the hash string.
        // This prevents runtime exceptions if older users were hashed with Argon.
        'verify' => false,
    ],

    'argon' => [
        'memory' => 65536,
        'threads' => 1,
        'time' => 4,
    ],
];

